### ISSUE TITLE
[Feature Request] Adding `askpass` Support

### ISSUE THREAD

**Issue by ThisNekoGuy** [Duncaen/OpenDoas#103]
Sudo has support for request a GUI password frontend like `ksshaskpass` via `sudo.conf`; it would be nice to have that equivalent functionality in `doas.conf` as well.

**Comment by Duncaen** [comment]
This is out of scope for opendoas as its a port of doas, I generally don't add features not present in upstream. In general doas is supposed to be simple and has a limited feature scope, for everything else there is always sudo, which works well and is widely used.

**Comment by ThisNekoGuy** [comment]
@Duncaen I won't dispute the point of doas being meant to be simple but the point of using doas _at all_ on a Linux system basically comes down to whether or not you're okay with sudo's frequent vulnerabilities, which makes that argument moot.
As a port, I don't see the problem with it being supported the same way you've cut out `persist`; you've done it once so I don't see why an opt-in feature would be somehow worse?

**Comment by Duncaen** [comment]
Adding new features that spawn programs, require certain environment variables to be exported to them before the user is authenticated is not really something I want to implement in a simple port.

There is nothing that makes doas more secure than sudo, except the feature scope. Adding features to a random port will just result in fragmentation and the feature being potentially a lot less safe than whatever lands in upstream, at least openbsd has people reviewing their patches, I have no idea if there are more than like a few people who have ever reviewed opendoas to be honest so making statements about this or that being more _secure_ is not really something I do (See also first point in the [Warnings section of the readme](https://github.com/Duncaen/OpenDoas#building-and-installation-warnings)).

The `perists` keyword (which can be enabled through a `configure` flag in this port) will just be ignored if not enabled at build time, the configuration file stays the same and the behavior is basically the same.
This is quite different from adding additional features, especially if I don't feel confident about them or don't actually use them.

The general goal of this port has always been to **_port_** doas to linux, not to build my own sudo replacement and piggyback off of the doas source code and name.
