### ISSUE TITLE
`question:` How to run nobody under root ?

### ISSUE THREAD

**Issue by ghost** [Duncaen/OpenDoas#104]
How can I build packages under root, as **nobody** ?
```
#[/home/mpk]# doas -u nobody makepkg
doas: Operation not permitted
```
Makepkg usually has restrictions, even when I run it under a user
```
$[~]$ doas -u nobody makepkg
==> ERROR: You do not have write permission for the directory $BUILDDIR (/tmp/makepkg).
    Aborting...
```
Works on sudo perfectly btw

**Comment by Duncaen** [comment]
You have to configure rules for that.

Either allow root to run things as any user:
```
permit root
```
or allow root to use a specific target user:
```
permit root as nobody
```

**Comment by ghost** [comment]
Tqvm
`permit root` in config, then `chown -R nobody /tmp/makepkg` fixed it.

**Comment by mckaygerhard** [comment]
Thanks this error must be put in manpage i try to search and search the `doas: Operation not permitted`  when run as root but foudn it..
