### ISSUE TITLE
`go build` fails when using `doas`

### ISSUE THREAD

**Issue by Witcher01** [Duncaen/OpenDoas#112]
Common in Makefiles, running `doas make install` to install a binary errors out because it calls `go build`:

```
error obtaining VCS status: exit status 128
        Use -buildvcs=false to disable VCS stamping.
```

This doesn't happen with sudo.

Steps to reproduce:
- `git clone https://git.sr.ht/~rjarry/aerc`
- `cd aerc`
- `doas make install`

**Comment by Duncaen** [comment]
I don't see how this has anything to do with doas, doas executes the command as root, if your command is broken when run as root then its not doas's fault and there is nothing that does can do or does wrong.

**Comment by Witcher01** [comment]
I'm not sure how doas works exactly and in what way it is different to sudo exactly.
What I'm asking myself is why does sudo work then?

Feel free to close this if it isn't a bug in doas.

**Comment by Duncaen** [comment]
Looks like this comes from git addressing a security issue where you run git command as root in a git directory clones/owned by a different user.

git has a workaround that uses `SUDO_UID` to detect the executing user and matches that instead: https://github.com/git/git/commit/ae9abbb63eea74441e3e8b153dc6ec1f94c373b4

https://github.blog/2022-04-12-git-security-vulnerability-announced/

I don't think there is anything opendoas can do about that, I don't really want to divert from upstream and set sudo environment variables as a workaround for some specific program.


I guess you could work around this by writing a doas rule for your specific user that sets the right `SUDO_UID`:
```
permit setenv { SUDO_UID=1000 } duncan
```

**Comment by Witcher01** [comment]
Interesting, thanks for looking into this issue.
The workaround indeed works, and I've opted to use that for my user.

Thanks again!
