### ISSUE TITLE
arguments not passed

### ISSUE THREAD

**Issue by Arnaudv6** [Duncaen/OpenDoas#115]
Hi and thanks for awesome software.
cryptsetup has weird order for its (long / non-posix) arguments, and doas doesn't take it, it seems?
``` shell
> doas cryptsetup luksHeaderBackup /dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --header-backup-file /tmp/xxxxxxxx-luks.header
doas (user@hostname) password:
Option --header-backup-file is required.
```

**Comment by Duncaen** [comment]
This is not doas, doas' option parsing happens at the beginning, long before asking for a password and will stop at the first non argument, so "cryptsetup", everything else is passed through verbatim.

**Comment by Arnaudv6** [comment]
You're right: I tried with a real root login, and my command fails also.
Failure coincided with me dropping sudo for doas, I should have checked sorry for the noise.
Closing as invalid.

**Comment by Arnaudv6** [comment]
In the (unlikely) event that someone messes up the same way I did:
my minimal out-from-the-web start-with doas config was not minimal enough:
```
permit :wheel
# commenting following line solved my issue:
# permit keepenv :wheel
```
_**Note to the curious geek:**_
Actually running the exact same command without doas:
```
cryptsetup luksHeaderBackup /dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --header-backup-file /tmp/xxxxxxxx-luks.header
```
prints the same very un-specific error: `Option --header-backup-file is required.`
Accidentally, my verbose doas config was not blocking on any other command I tried.
