### ISSUE TITLE
doas doesn't work with [[ in bash

### ISSUE THREAD

**Issue by peterwu** [Duncaen/OpenDoas#121]
```
$ [ -e ~/testfile ]        # good
$ [[ -e ~/testfile ]]      # good
$ doas [ -e ~/testfile ]   # good
$ doas [[ -e ~/testfile ]] # error below
doas: [[: command not found
```

**Comment by Duncaen** [comment]
`[[` is a bash builtin, `[` also exists as binary, doas does not know or try to attempt to execute commands it can't find in `PATH` in a shell.

You'll have to explicitly run it in a bash shell if you want to do this: `doas bash -c '[[ -e ~/testfile ]]'`.
