### ISSUE TITLE
Keywords can conflict with user names

### ISSUE THREAD

**Issue by Earnestly** [Duncaen/OpenDoas#13]
For this simple example we have a user called `nopass`:

```
# /etc/doas.conf
permit nopass nopass as wheel
```

Running `doas -C /etc/doas.conf` will result in syntax errors (`syntax error at line 1`).

This likely extends to all the keywords such as `keepenv`.  Is there a workaround or is this a known limitation of the grammar?

**Comment by Duncaen** [comment]
It seems to work if you put the username in quotes e.g.
```
[nopass ~]$ cat test.conf
permit nopass "nopass" cmd id
[nopass ~]$ doas -C test.conf id
permit nopass
```

**Comment by Earnestly** [comment]
Ah, I thought there might be something to handle this situation but I didn't square the concept of quoting with it.  Thanks for experimenting too.  I'll close this now as it seems to satisfy the original question.
