### ISSUE TITLE
More useful parse errors

### ISSUE THREAD

**Issue by Earnestly** [Duncaen/OpenDoas#15]
Currently the function [`yyerror()`](https://github.com/Duncaen/OpenDoas/blob/master/parse.y#L197) could prefix the program's name, like `err()` does.

Seeing simply `syntax error at line 1` in a stream doesn't help very much.

**Comment by Duncaen** [comment]
https://github.com/Duncaen/OpenDoas/commit/dbac3f3cfda4559cdf356313575fac33208afae7
