### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by escondida** [Duncaen/OpenDoas#19]
Excellent work on OpenDoas!

Are there any plans for a new release in the near future, and/or are there any outstanding issues blocking a release?

**Comment by escondida** [comment]
@Duncaen, thanks again for merging in my minor stuff today! With the additional merge of timeout support for PAM, is there anything blocking an official release? I'd like to put a version with persist into Archlinux's [community] repo at some point.

I'm happy to (at least attempt to) help with any outstanding issues blocking a release.

**Comment by Duncaen** [comment]
I would like to have some people review and test the timestamp stuff before it goes into a official release, I've been testing it myself for over a year now without problems, but as it is a very security critical feature I would like to avoid releasing it with issues.

**Comment by Duncaen** [comment]
Updating the https://github.com/Duncaen/OpenDoas#about-the-port would be something I think should be done before the release too, I don't have any Mac OS X systems and I doubt that it still works.

**Comment by Earnestly** [comment]
A day late on this issue but I'll get updated and give this a test as wel.

**Comment by cinerea0** [comment]
Just wondering, has there been any progress made towards the new release?

**Comment by escondida** [comment]
Thanks for the release! It looks like you can also close #17.

**Comment by Earnestly** [comment]
Since I wrote that I would be testing this, I can report that there has been no issues thus far.

**Comment by escondida** [comment]
Ditto. I've been working off the git with timestamps enabled this whole time.

Nevertheless, since I respect your caution, I did include your warning about timestamps in the installation output of the new Arch package.

**Comment by cinerea0** [comment]
@escondida Are you sure that's necessary? I'm using the 6.6 release now in a different distro (Void, not Arch), and while the persist keyword no longer produces an error when used, it also doesn't seem to provide timestamp functionality.

**Comment by Duncaen** [comment]
The void package is currently build without timestamp support.

**Comment by cinerea0** [comment]
@Duncaen Thank you for clearing up my confusion!
