### ISSUE TITLE
REQ: sssd integration

### ISSUE THREAD

**Issue by FatmanUK** [Duncaen/OpenDoas#25]
My use case: currently I have sudo configured to retrieve its rules from FreeIPA via sssd/nss. I'd like to replace sudo. As I had to recompile sudo with "--with-sssd", I assume there is something that needs to happen in doas to achieve this.

I haven't looked at the sudo source yet. I also assume support would be needed from the sssd and FreeIPA projects --- perhaps I have this backwards, but I thought OpenDoas would be the place to start.

Thanks for reading.

**Comment by Duncaen** [comment]
I don't think I'm personally interested in adding any extra features for that, if it just needs some changes to pam to make it work with a pam module then maybe its possible.
