### ISSUE TITLE
Support the -v argument

### ISSUE THREAD

**Issue by Kommynct** [Duncaen/OpenDoas#29]
Sudo has a -v argument, this allows the use of --sudoloop in yay unless there's an equivalent and I'm stupid.

**Comment by Duncaen** [comment]
I don't really want to add flags or configuration options to this port unless they are supported by upstream.

I think in this case its better to ask the yay maintainers for a configuration option to change the behavior, most parts about the stuff is already configurable.

**Comment by Kommynct** [comment]
Would you be willing to help the yay team with your expertise? I don't know how a sudoloop could work otherwise or I'd figure it out

**Comment by Duncaen** [comment]
I would propose `--sudoupdateflags` with the default of `-v` for sudo and then for doas you could set `--sudoupdateflags=true` so that it just calls `doas true` or whatever you provide in the loop.
