### ISSUE TITLE
`make install` doesn't work

### ISSUE THREAD

**Issue by frgm** [Duncaen/OpenDoas#3]
I get:
```
...
+ make install DESTDIR=/home/pkgmk/work/doas/pkg
fatal: Not a git repository (or any parent up to mount point /home/pkgmk/work)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
cp doas .doas.chmod
chown root:wheel .doas.chmod
chmod 4511 .doas.chmod
mv .doas.chmod /home/pkgmk/work/doas/pkg/usr/bin/doas
mv: cannot move '.doas.chmod' to '/home/pkgmk/work/doas/pkg/usr/bin/doas': No such file or directory
bsd.prog.mk:28: recipe for target '/home/pkgmk/work/doas/pkg/usr/bin/doas' failed
make: *** [/home/pkgmk/work/doas/pkg/usr/bin/doas] Error 1
rm .doas.chmod
=======> ERROR: Building '/home/pkgmk/packages/doas#git-e246f9e-1.pkg.tar.xz' failed.
```
I was trying to build it via the CRUX Pkgfile:
```
# Description: OpenDoas

name=doas
version=git-e246f9e
release=1
source=(https://github.com/Duncaen/OpenDoas/archive/${version:4:13}.tar.gz)

build() {
        cd OpenDoas-${version:4:13}*
        ./configure
        make
        make install DESTDIR=$PKG
}
```

to easily manage this pkg.

How about to change the `install` target to something like this:
```
install:
  mkdir -p -m 0755 ${DESTDIR}${BINDIR}
  mkdir -p -m 0755 ${DESTDIR}${PAMDIR}
  mkdir -p -m 0755 ${DESTDIR}${MANDIR}/man{1,5}

  cp -f doas ${DESTDIR}${BINDIR}
  chown ${BINOWN}:${BINGRP} ${DESTDIR}${BINDIR}/doas
  chmod ${BINMODE} ${DESTDIR}${BINDIR}/doas

  cp -f ${PAM_DOAS} ${DESTDIR}${PAMDIR}/doas
  chmod 0444 ${DESTDIR}${PAMDIR}/doas/${PAM_DOAS}

  cp -f doas.1 ${DESTDIR}${MANDIR}/man1
  chmod 0444 ${DESTDIR}${MANDIR}/man1/doas.1

  cp -f doas.conf.5 ${DESTDIR}${MANDIR}/man5
  chmod 0444 ${DESTDIR}${MANDIR}/man5/doas.conf.5
```

**Comment by frgm** [comment]
++ `configure` script doesn't understand env variable options:
`./configure CFLAGS='-O2 -pipe'`

I was thinking of adding something like this:
```patch
        --help|-h) usage;;
-       *) die "Error: unknown option $opt";;
+       -*) die "Error: unknown option $opt";;
+       *) eval $opt='$var';;
        esac
```
but that's not perfect.

How about to change configure usage to just
`usage: configure [options]`, without `[settings]`?

env vars should go before `configure` script

**Comment by frgm** [comment]
+++
How about to set default value of `DESTDIR` to an empty string ?

**Comment by Duncaen** [comment]
I'm all in with simplifying the makefile and changed it to your suggestion in 09843fcf8876df1ab1728e9c2c49de4836b25626.
To pass variables to the configuration script you can do one of the following:
`CFLAGS='-O2 -pipe' ./configure`
`export CFLAGS='-O2 -pipe'; ./configure`

Not sure if its the right time to package it already, as I just noticed a very bad issue i introduced and fixed in https://github.com/Duncaen/OpenDoas/commit/9972a8ee4233ba9e48f70b7d21dbf1fb395f136e.

**Comment by frgm** [comment]
oops, my example was with  bug, here is [PR#4](https://github.com/Duncaen/OpenDoas/pull/4).
