### ISSUE TITLE
persist option does not work

### ISSUE THREAD

**Issue by ArcticTheRogue** [Duncaen/OpenDoas#32]
I am using this config:
```
permit persist keepenv arctic as root
```
Though when I try to use doas multiple times in a row I have to enter my password every time still.
I am using version 6.6.1 installed from Gentoo repos.

**Comment by Duncaen** [comment]
This has to be enabled explicitly at build time by running configure with `--with-timestamp`, the gentoo build doesn't do that.

**Comment by ArcticTheRogue** [comment]
Okie doke thanks
