### ISSUE TITLE
OpenDoas keepenv on macOS

### ISSUE THREAD

**Issue by grylem** [Duncaen/OpenDoas#44]
Hi
doas.conf contains the line -' permit keepenv grylem as root'
But vim does not recognize .vimrc etc in grylem $HOME if run 'doas vim file'
Regards.

**Comment by Duncaen** [comment]
The big reason to not do this is that you would backdoor yourself by allowing to blindly execute your vimrc, or your shells profile when running commands as root with doas.

You need to use `setenv` if you really want to keep those environment variables i.e. `setenv { HOME USER }`,
`keepenv` is for anything that is not already explicitly set:
https://github.com/Duncaen/OpenDoas/blob/31abd37c26c26892ce5e0d538c51fbc38ff3e05a/env.c#L106-L111
