### ISSUE TITLE
doas thunar failing

### ISSUE THREAD

**Issue by chromer030** [Duncaen/OpenDoas#49]
Hi , Thunar (and all other components of xfce desktop ) cant be run with doas , running with sudo is OK.
Arch Linux , Kernel 5.10.11 , XFCE 4.16 , opendoas 6.8.1

/etc/doas.conf :
```
permit persist :wheel
```

Error log :
```
$ doas thunar
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused

(thunar:6902): Gtk-WARNING **: 18:03:16.326: cannot open display: :0.0
$ _
```

```
$ doas xfce4-terminal    
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused

(xfce4-terminal:7674): Gtk-WARNING **: 18:09:50.338: cannot open display: :0.0
$ _
```

(I'm not sure if this is fault of XFCE or Doas.)

**Comment by Duncaen** [comment]
First off I don't think its a good idea to run thunar as root.

> (I'm not sure if this is fault of XFCE or Doas.)

Yours, you need to configure the rule to allow to pass through environment variables like `DISPLAY` and `XAUTHORITY` using setenv option.
