### ISSUE TITLE
What is the difference between opendoas and the doas in AUR?

### ISSUE THREAD

**Issue by laichiaheng** [Duncaen/OpenDoas#50]
Are they different?

**Comment by owl4ce** [comment]
Dude, AUR is based on [this](https://github.com/slicer69/doas). But I'm also curious.

**Comment by Duncaen** [comment]
The other doas port does not support persist and added new features like vidoas which were implemented in a insecure way.

There have also been a number of pretty beginner level security issues which were addressed in commits with misleading titles and downplaying the severity:
- https://github.com/slicer69/doas/commit/261c2164496dbebe6e3e7191db3dd7c840f6af58
- https://github.com/slicer69/doas/commit/2f83222829448e5bc4c9391d607ec265a1e06531

**Comment by laichiaheng** [comment]
Open is better.

**Comment by alt-art** [comment]
Bullshit.
