### ISSUE TITLE
Doas does not handle variables well

### ISSUE THREAD

**Issue by Managor** [Duncaen/OpenDoas#55]
When trying to use for example `visudo` with `nano` and doing it with `sudo`, sudo handles it just fine when written as `sudo EDITOR=nano visudo`. `doas` on the other hand complains `doas: EDITOR=nano: command not found` when attempting to run `doas EDITOR=nano visudo`

**Comment by Duncaen** [comment]
That is just not supported, `doas` will execute the command as a command.
If you want to use variables, like in a shell, use the shell or allow the rule to pass through variables.

```
doas sh -c 'EDITOR=nano visudo'
```
