### ISSUE TITLE
permit extended command

### ISSUE THREAD

**Issue by dkwo** [Duncaen/OpenDoas#58]
What is the correct syntax to permit a command like
```
/usr/bin/xi -Su
```
in doas.conf?
If I try with single quotation marks ' it gives an error.
```
stat -c %a /etc/doas.conf
440
```
```
cat /etc/doas.conf
permit :wheel
permit nopass dkwo cmd /usr/bin/brightness
permit nopass dkwo cmd /usr/bin/reboot
permit nopass dkwo cmd /usr/bin/poweroff
```
Thanks.

**Comment by owl4ce** [comment]
> What is the correct syntax to permit a command like
> 
> ```
> /usr/bin/xi -Su
> ```
> 
> in doas.conf?
> If I try with single quotation marks ' it gives an error.
> 
> ```
> stat -c %a /etc/doas.conf
> 440
> ```
> 
> ```
> cat /etc/doas.conf
> permit :wheel
> permit nopass dkwo cmd /usr/bin/brightness
> permit nopass dkwo cmd /usr/bin/reboot
> permit nopass dkwo cmd /usr/bin/poweroff
> ```
> 
> Thanks.

Mine

![image](https://user-images.githubusercontent.com/53987136/108511094-f9e2b080-72f1-11eb-8774-f0186282c1fc.png)

**Comment by Duncaen** [comment]
permit nopass dkwo cmd /usr/bin/xi args -Su

**Comment by dkwo** [comment]
Thank you.

**Comment by dkwo** [comment]
If I remove `sudo`, then something weird happens:
```
[nicolo@mabragor ~]$ groups nicolo
nicolo : nicolo wheel
[nicolo@mabragor ~]$ cat /etc/doas.conf
permit :wheel
permit nopass :wheel cmd /usr/bin/reboot
permit nopass :wheel cmd /usr/bin/xi args -Su
[nicolo@mabragor ~]$ xi -Su
doas (nicolo@mabragor) password:
```
Do you know why it is asking for password?

**Comment by Duncaen** [comment]
You are executing `xi` without `doas`, `xi` itself executes `doas xbps-install`.

**Comment by dkwo** [comment]
Thanks, but still
```
[nicolo@mabragor ~]$ doas reboot
doas (nicolo@mabragor) password:

[nicolo@mabragor ~]$ doas xi -Su
doas (nicolo@mabragor) password:
```

**Comment by Duncaen** [comment]
probably because PATH prefers `/bin` over `/usr/bin`, so don't specify the full path in `doas.conf`, i.e.:
```
permit nopass :wheel cmd xi args -Su
```

**Comment by dkwo** [comment]
Still something I do not understand:
```
[nicolo@mabragor ~]$ cat /etc/doas.conf
permit :wheel
permit nopass :wheel cmd /usr/bin/reboot
permit nopass :wheel cmd xi args -Su
[nicolo@mabragor ~]$ doas xi -Su
doas: Operation not permitted
[nicolo@mabragor ~]$ xi -Su
doas (nicolo@mabragor) password:
```

**Comment by Duncaen** [comment]
Test with `doas -C /etc/doas.conf xi -Su`, also is xi installed in /usr/bin or in your own path, or is it a alias or something like that?

**Comment by dkwo** [comment]
Now I get
```
[nicolo@mabragor ~]$ doas -C /etc/doas.conf xi -Su
permit
[nicolo@mabragor ~]$ doas xi -Su
doas (nicolo@mabragor) password:
```
`xi` is intalled by xtools regular package

**Comment by dkwo** [comment]
What should be the correct line in `/etc/doas.conf` that allows a user in `wheel` to just use `xi -Su`?

**Comment by Duncaen** [comment]
```
permit :wheel as root cmd xi args -Su
```

**Comment by Duncaen** [comment]
The last rule that matches applies, so the order is important.

**Comment by dkwo** [comment]
With that, it still asks me for password:
```
[nicolo@mabragor ~]$ cat /etc/doas.conf
permit :wheel
permit nopass :wheel cmd /usr/bin/reboot
permit :wheel as root cmd xi args -Su
[nicolo@mabragor ~]$ xi -Su
doas (nicolo@mabragor) password:
```

**Comment by dkwo** [comment]
is it working differently for you?

**Comment by dkwo** [comment]
(What I meant is: being able to use `xi -Su` without being asked for password.)

**Comment by Duncaen** [comment]
You asked for allows a user to use, it will ask for the password, add `nopass` if you don't want to be asked.

**Comment by dkwo** [comment]
Still, I get asked for it
```
[nicolo@mabragor ~]$ cat /etc/doas.conf
permit :wheel
permit nopass :wheel cmd /usr/bin/reboot
permit nopass :wheel as root cmd xi args -Su
[nicolo@mabragor ~]$ xi -Su
doas (nicolo@mabragor) password:
```

**Comment by Duncaen** [comment]
This allows you to execute  `doas xi -Su`.

To allow just `xi -Su` you would have to whitelist all arguments the xi script adds to the rule, which includes relative directories as repositories so it won't be safe.

**Comment by dkwo** [comment]
I see, but not even that works:
```
[nicolo@mabragor ~]$ doas xi -Su
doas: Operation not permitted
```

**Comment by dkwo** [comment]
is it enough to just edit the file, or am I supposed to restart something for the change to take effect?

**Comment by Duncaen** [comment]
```
cat /etc/doas.conf
doas -C /etc/doas.conf xi -Su
which xi
echo $PATH
```

**Comment by dkwo** [comment]
```
[nicolo@mabragor ~]$ cat /etc/doas.conf
permit :wheel
permit nopass :wheel cmd /usr/bin/reboot
permit nopass :wheel as root cmd xi args -Su
[nicolo@mabragor ~]$ doas -C /etc/doas.conf xi -Su
permit nopass
[nicolo@mabragor ~]$ type xi
xi is /usr/bin/xi
[nicolo@mabragor ~]$ which xi
/usr/bin/xi
[nicolo@mabragor ~]$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin
[nicolo@mabragor ~]$ doas xi -Su
doas: Operation not permitted
```

**Comment by Duncaen** [comment]
its xi executing doas again as root. https://github.com/leahneukirchen/xtools/pull/208

**Comment by Duncaen** [comment]
You could work around this by allow root to execute it as root until there is a release of xtools.

```
permit nopass root as root
```

**Comment by dkwo** [comment]
I see, many thanks for helping with this!
