### ISSUE TITLE
Piping output causes doas to hang

### ISSUE THREAD

**Issue by moshiur-raj** [Duncaen/OpenDoas#63]
Recetly I tried to pipe a nftables output to neovim and noticed that doas hung up. It seems piping anything causes this issue.
Try :
`doas echo hello | nvim`

Redirecting the output to a file (eg `doas echo hello > newfile`) works file though.
Is this expected behaviour?
This does not happen with sudo.

I am using opendoas 6.8.1 in arch linux.

**Comment by Duncaen** [comment]
I don't see a difference with sudo, if the password is prompted and there is a second process messing with the terminal then things are going to be weird visually.
In your tests I assume sudo did not prompt for a password.

**Comment by moshiur-raj** [comment]
You're right. Sudo did not prompt me for a password.
