### ISSUE TITLE
getpwuid_r failed: no such file or directory

### ISSUE THREAD

**Issue by dev-kittens** [Duncaen/OpenDoas#65]
Hi, I am trying to use opendoas with `/etc/shadow`, but I am getting the error: `doas: getpwuid_r failed: No such file or directory`.
I can reproduce the error with the example program from the `getpwuid_r` documentation. However, while trying to build that, I noticed the following linker warning: 
> `warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking`

I am not very familiar with this, is there a way I can statically compile opendoas and not need to include shared libraries on the target machine?

**Comment by dev-kittens** [comment]
I was able to fix this by compiling with musl libc instead of glibc.

**Comment by Duncaen** [comment]
Yes not using glibc is the only solution, all the functions to get users, shadow entries, groups and some other things with glibc will require glibc at runtime because of nss and I don't think there is a way to disable that.
