### ISSUE TITLE
ZSH aliases when using doas 

### ISSUE THREAD

**Issue by ethanh92** [Duncaen/OpenDoas#66]
How should I configure setenv in doas.conf to preserve my .zshrc aliases? I have set my $ZDOTDIR to ~/.config/zsh if that's relevant at all.

Figured it out. Adding the alias doas='doas ' to my .zshrc does the trick.

**Comment by Duncaen** [comment]
Aliases are internal to your shell and not passed through the environment, doas can't do anything about them.

Not sure what exactly the issue was, but since it is resolved I'm closing this.
