### ISSUE TITLE
fork+exec instead of exec!?

### ISSUE THREAD

**Issue by l29ah** [Duncaen/OpenDoas#68]
Why doesn't doas `execve` the target binary without forking? Is there a reason that doas process needs to persist during all the execution time of the executed command?

**Comment by Duncaen** [comment]
This is done if pam is used for authentication to keep a session open until the process exits.

**Comment by l29ah** [comment]
Ah, ok, it doesn't keep going when built w/o PAM and is only needed to trigger PAM hooks at the session end, if any; thanks!
