### ISSUE TITLE
Man page section wrong?

### ISSUE THREAD

**Issue by SynergyBest** [Duncaen/OpenDoas#77]
If I'm not mistaken wouldn't the doas command manual page go into section 8? To quote man's manual page '8 System Administration Commands' and doas seems like a system administration command to me (and sudo I guess.)

**Comment by ericonr** [comment]
https://man.bsd.lv/doas.1 puts it in section 1...

**Comment by SynergyBest** [comment]
Maybe I have the audacity to say they are wrong. Anyways, I guess I’ll close this, I really was just wondering but discussions aren’t enabled so this seemed like the best place to put it.
