### ISSUE TITLE
build error on arch.

### ISSUE THREAD

**Issue by OldWorldOrdr** [Duncaen/OpenDoas#78]
```
yacc  parse.y
make: yacc: No such file or directory
make: *** [<builtin>: parse.c] Error 127
```

happens when installing from aur or when building manually

**Comment by OldWorldOrdr** [comment]
i litterally cannot build opendoas cuz of this

**Comment by ericonr** [comment]
Install `bison`. That error tells you you're missing the `yacc` executable, which is provided by that package.

https://archlinux.org/packages/core/x86_64/bison/
