### ISSUE TITLE
Authentication failed 

### ISSUE THREAD

**Issue by Baitinq** [Duncaen/OpenDoas#81]
I am encountering the authentication failed prompt as soon as executing doas on arch linux, it doesnt even ask for any password, just exists with that error.

Any one else can confirm this behavior?

**Comment by Duncaen** [comment]
> Any one else can confirm this behavior?

No this would have popped up already. How did you install opendoas, anything special about your pam setup?

**Comment by Baitinq** [comment]
> > Any one else can confirm this behavior?
> 
> No this would have popped up already. How did you install opendoas, anything special about your pam setup?

I simply installed it by running ./configure && make && make install

After running it on a second device I can confirm that it is indeed a problem specific to the first device, ill try and solve it or just reinstall, as as far as i know i havent messed with pam at all.

Thank you

**Comment by Duncaen** [comment]
You need to configure pam, there is a package in the arch repository, would probably suggest to just use that as it ships with the pam configuration, you might have it installed on the second system.

https://github.com/Duncaen/OpenDoas#pam-configuration
