### ISSUE TITLE
Option to Ask for Password Again Upon a Failure?

### ISSUE THREAD

**Issue by Amarakon55** [Duncaen/OpenDoas#85]
When I type the wrong password, I have to run the command again which is rather inconvenient. I would like for an option to be able to ask again for the password upon failure. 

As a workaround, I can do this:
doas <command> || doas <command>

That will ask for the password only one more time. I don't want to add a million exit codes.

**Comment by Duncaen** [comment]
https://github.com/Duncaen/OpenDoas/issues/82
