### ISSUE TITLE
Xt error: Can't open display: %s

### ISSUE THREAD

**Issue by purpleleaf** [Duncaen/OpenDoas#89]
Running X applications with doas on a fresh Artix base install, report the following error:

```
Invalid MIT-MAGIC-COOKIE-1 keyWarning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
```

**Comment by Duncaen** [comment]
This has nothing to do with doas, you have to 1. configure Xorg to allow other users access, 2. configure the environment or configure doas to pass through any required environment variables (`DISPLAY`, `XAUTHORITY`).

**Comment by purpleleaf** [comment]
Hi Duncaen,
i don't run xorg as root. The error reported occurs running  "doas xterm" (or any other x11 application) from inside an existing xterm instance.
The environment variable needed to correctly run xorg are all set (i use lightdm). Anyway i will try to report thiss error to the Arch package manteiner.

**Comment by ericonr** [comment]
>  The error reported occurs running "doas xterm" (or any other x11 application) from inside an existing xterm instance.

That's what you're doing wrong. You shouldn't be running X11 *applications* as root. And if you want to do so, you need to configure `doas` to export those variables to programs it launches or do some other trick (like calling `doas env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY xterm`).

There's absolutely nothing wrong with the package.

**Comment by purpleleaf** [comment]
Tanks for the explanation, I understand your point, but all the linux distro i've used until now were usually configured to run X11 application using sudo or pkexec, so I thought that doas beahved like all those other utilities and it should work that way out of the box.
Anyway i configured doas.conf with keepenv. Is this less secure then exporting only the Xautority path?

**Comment by ericonr** [comment]
Not really, if your user can use any command you could just use `env` to export some variables.
