### ISSUE TITLE
Persist does not work on Arch

### ISSUE THREAD

**Issue by ad-on-is** [Duncaen/OpenDoas#94]
I've installed opendoas from the Arch repo which seems to be built with the  `--with-timestamp` config.
https://github.com/archlinux/svntogit-community/blob/packages/opendoas/trunk/PKGBUILD

However, the password is not persisted, even thou I've added `permit persist :wheel` in the /etc/doas.conf

Is there something I'm missing?

**Comment by ad-on-is** [comment]
Ok, I found the issue.. It's the ordering of settings.

This **does not** work
```
permit persist :wheel
permit setenv { XAUTHORITY LANG LC_ALL } :wheel
```

However, this **works**

```
permit setenv { XAUTHORITY LANG LC_ALL } :wheel
permit persist :wheel
```

**Comment by ericonr** [comment]
You're overriding the config for `:wheel`, that should be a single line with all the configs.
