### ISSUE TITLE
doas prints pam conversation to stdout

### ISSUE THREAD

**Issue by eternal-sorrow** [Duncaen/OpenDoas#95]
I use `pam_fprintd` PAM module for fingerprint authentication. It works mostly fine, bu I have one issue. Whenever I try to do something like `doas command > file`, the fprintd prompt line "_Place your finger on the fingerprint reader_" gets redirected to the file along with the command output. Fprintd [issue](https://gitlab.freedesktop.org/libfprint/fprintd/-/issues/17) says it was fixed with sudo (I tested, and it indeed is), but I still get this problem with doas.

**Comment by gcb** [comment]
fix looks right, but still see the bad behaviour on `opendoas 6.8.2-1`

i get output of pam/fingerprintd in my stdout.

**Comment by fossdd** [comment]
> fix looks right, but still see the bad behaviour on `opendoas 6.8.2-1`

The commit is unreleased. I'm using the Arch Linux package (looks like you aswell) and they don't include the patch.

It would be awesome if @Duncaen could release a new stable release, so disitobutions can pick it up. :-)
