### ISSUE TITLE
[Bug Report] Incorrect result when using "-C" option

### ISSUE THREAD

**Issue by asukakenji** [Duncaen/OpenDoas#97]
I tested this on a real machine with freshly installed Alpine Linux 5.15.30-0-lts (latest version at the time writing). The version of `doas` was `doas-6.8.1-r7`.

# Summary

In all of the following tests, the configs actually worked fine no matter if the privilege was granted to a user or a group, but the results of the `-C` tests were incorrect unless the privilege was granted to the `wheel` group.

# Tests

I had a user named `tester`:
```
# id tester
uid=1000(tester) gid=1000(tester) groups=1000(tester)
```

I had a one-line config `tester.conf`:
```
# cat /etc/doas.d/tester.conf
permit tester
```

When I logged in as `root` and tested the config with the `-C` option, it said `deny`:
```
# doas -C /etc/doas.d/tester.conf -u tester -- ls -al /root
deny
```

However, when I logged in as `tester` and executed the same command, it actually worked fine:
```
$ whoami
tester
$ doas -- ls -al /root
doas (tester@localhost) password: 
total 12
drwx------    2 root     root          4096 Mar 26 01:17 .
drwxr-xr-x   22 root     root          4096 Mar 26 00:35 ..
-rw-------    1 root     root          3452 Mar 26 13:52 .ash_history
```

The following config gave the same result:
```
# cat /etc/doas.d/tester.conf
permit tester as root
# doas -C /etc/doas.d/tester.conf -u tester -- ls -al /root
deny
```

The following config also gave the same result (changed from `tester` user to `tester` group):
```
# cat /etc/doas.d/tester.conf
permit :tester
# doas -C /etc/doas.d/tester.conf -u tester -- ls -al /root
deny
```

Modifying `/etc/doas.d/doas.conf` directly gave the same result too, so it seems that it is not related to the unusual config location (`/etc/doas.conf` is a symlink to `/etc/doas.d/doas.conf` on Alpine Linux).

Here is the listing of the config files:
```
# ls -la /etc/doas.conf
lrwxrwxrwx    1 root     root            21 Mar 26 01:00 /etc/doas.conf -> /etc/doas.d/doas.conf
# ls -la /etc/doas.d
total 20
drwxr-x---    2 root     root          4096 Mar 26 13:34 .
drwxr-xr-x   32 root     root          4096 Mar 26 14:05 ..
-rw-------    1 root     root           192 Mar 26 13:50 doas.conf
-rw-------    1 root     root            22 Mar 26 14:20 tester.conf
-rw-------    1 root     root            22 Mar 26 06:13 wheel.conf
```

I had another user named `asukakenji`:
```
# id asukakenji
uid=501(asukakenji) gid=20(dialout) groups=20(dialout),10(wheel)
```

It gave similar result when I granted the privilege to the user `asukakenji` (note `deny`):
```
# cat /etc/doas.d/wheel.conf
permit asukakenji
# doas -C /etc/doas.d/wheel.conf -u asukakenji -- ls -al /root
deny
```
```
$ whoami
asukakenji
$ doas -- ls -al /root
doas (asukakenji@localhost) password: 
total 16
drwx------    2 root     root          4096 Mar 26 01:17 .
drwxr-xr-x   22 root     root          4096 Mar 26 00:35 ..
-rw-------    1 root     root          4977 Mar 26 14:36 .ash_history
```

However, when I granted the privilege to the group `wheel`, the result was correct (note `permit` instead of `deny`):
```
# cat /etc/doas.d/wheel.conf
permit :wheel
# doas -C /etc/doas.d/wheel.conf -u asukakenji -- ls -al /root
permit
```
```
$ whoami
asukakenji
$ doas -- ls -al /root
doas (asukakenji@localhost) password: 
total 16
drwx------    2 root     root          4096 Mar 26 01:17 .
drwxr-xr-x   22 root     root          4096 Mar 26 00:35 ..
-rw-------    1 root     root          5180 Mar 26 14:43 .ash_history
```

**Comment by Duncaen** [comment]
> ```
> # cat /etc/doas.d/tester.conf
> permit tester
> ```


This allows the user `tester` to use doas, the user `root` won't be allowed. The `-u` flag switches the target user, not the requesting user, who has to be permitted in the configuration.

**Comment by asukakenji** [comment]
> This allows the user `tester` to use doas, the user `root` won't be allowed. The `-u` flag switches the target user, not the requesting user, who has to be permitted in the configuration.

Okay. So, if I want to test whether `tester` can do something, I must login as `tester`. Is that correct?

Therefore, the reason why the following results in `permit` is that `root` itself being in the `wheel` group, right?

```
# cat /etc/doas.d/wheel.conf
permit :wheel
# doas -C /etc/doas.d/wheel.conf -u asukakenji -- ls -al /root
permit
```

I followed an incorrect tutorial from Gentoo, which suggests that `-u` can select the *source* user instead of the *target* user:

https://wiki.gentoo.org/wiki/Doas#Testing

Gentoo uses exactly this `doas`:

https://packages.gentoo.org/packages/app-admin/doas

If what I expected above is true, I will suggest them to correct the tutorial.

Please let me close this issue after your reply. Thanks!

**Comment by Duncaen** [comment]
Right as `root`, `doas -C /etc/doas.conf -u tester id` would check if `root` is allowed to execute `id` as `tester`, as configured with a rule like `permit root` that allows all target users or with `permit root as tester` allowing root to only use the specific target user.
